name: pizza_repository
description: Repo to handle pizzas
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  equatable:
#  firebase_auth:
  cloud_firestore:
  uuid:
#  firebase_storage:
#  rxdart:
#  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
